name: Build docker image
on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    strategy:
      matrix:
        project: [frontend, backend]
    name: Build and push ${{ matrix.project }} docker image
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.project }}/Dockerfile
          context: ${{ matrix.project }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/hitra-utleie:${{ matrix.project }}-production-latest
