name: Build docker image
on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: frontend/Dockerfile
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/hitra-utleie:frontend-production-latest
